name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Shellcheck
        run: sudo apt install shellcheck -y
      - name: Run shellcheck
        run: ./lint_scripts.sh
